apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: {{ .Values.metadata.name }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ .Values.metadata.name }}
  minReplicas: {{ .Values.autoscaler.min }}
  maxReplicas: {{ .Values.autoscaler.max }}
  targetCPUUtilizationPercentage: 50