apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: { { .Values.metadata.name } }
  annotations:
    kubernetes.io/ingress.class: "gce"
    kubernetes.io/ingress.global-static-ip-name: "ingress-static-ip"
spec:
  rules:
    - http:
        paths:
          - path: "/"
            pathType: ImplementationSpecific
            backend:
              service:
                name: { { .Values.metadata.name } }
                port:
                  number: { { .Values.configurations.port } }
