apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.metadata.name }}
spec:
  type: NodePort
  selector:
    app: {{ .Values.metadata.label }}
  ports:
    - port: {{ .Values.configurations.port }}
      targetPort: {{ .Values.configurations.port }}
