apiVersion: v1
kind: Secret
metadata:
  name: secret-tls
data:
  tls.crt: {{ .Files.Get "~/ssl-certificate/tls-cert-file"  | b64enc }} 
  tls.key: {{ .Files.Get "~/ssl-certificate/private-key-file"  | b64enc }}
type: kubernetes.io/tls