apiVersion: v1
kind: Secret
metadata:
  name: secret-tls
data:
  tls.crt: {{ .Values.security.tls.CertFile  | b64enc }} 
  tls.key: {{ .Values.security.tls.PrivateKeyFile  | b64enc }}
    
  
type: kubernetes.io/tls