apiVersion: v1
kind: Secret
metadata:
  name: secret-tls
data:
  tls.crt: {{ .Values.security.tls.CertFile  | base64}} 
  tls.key: {{ .Values.security.tls.PrivateKeyFile  | base64 }}
    
  
type: kubernetes.io/tls